// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcsQtMVaYTF9nRvj-Btebn05kK3dVDMlI',
    appId: '1:224775229543:web:c03e993a2c691c009784c2',
    messagingSenderId: '224775229543',
    projectId: 'stride-bc91f',
    authDomain: 'stride-bc91f.firebaseapp.com',
    databaseURL: 'https://stride-bc91f-default-rtdb.firebaseio.com',
    storageBucket: 'stride-bc91f.firebasestorage.app',
    measurementId: 'G-JHEJMDXN79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvY6jrYnE8tBzXU9G65lSUAlhqRwjjLB0',
    appId: '1:224775229543:android:dde095370168ccb09784c2',
    messagingSenderId: '224775229543',
    projectId: 'stride-bc91f',
    databaseURL: 'https://stride-bc91f-default-rtdb.firebaseio.com',
    storageBucket: 'stride-bc91f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPk2E_HOCzifO2bRfT2AvvXxBCbMCmcFY',
    appId: '1:224775229543:ios:9874d3a7a048b5ca9784c2',
    messagingSenderId: '224775229543',
    projectId: 'stride-bc91f',
    databaseURL: 'https://stride-bc91f-default-rtdb.firebaseio.com',
    storageBucket: 'stride-bc91f.firebasestorage.app',
    iosBundleId: 'com.example.stride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPk2E_HOCzifO2bRfT2AvvXxBCbMCmcFY',
    appId: '1:224775229543:ios:9874d3a7a048b5ca9784c2',
    messagingSenderId: '224775229543',
    projectId: 'stride-bc91f',
    databaseURL: 'https://stride-bc91f-default-rtdb.firebaseio.com',
    storageBucket: 'stride-bc91f.firebasestorage.app',
    iosBundleId: 'com.example.stride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcsQtMVaYTF9nRvj-Btebn05kK3dVDMlI',
    appId: '1:224775229543:web:282256303d31bd2e9784c2',
    messagingSenderId: '224775229543',
    projectId: 'stride-bc91f',
    authDomain: 'stride-bc91f.firebaseapp.com',
    databaseURL: 'https://stride-bc91f-default-rtdb.firebaseio.com',
    storageBucket: 'stride-bc91f.firebasestorage.app',
    measurementId: 'G-TYQ024J921',
  );
}
